# Dirección de tu base de datos (puerto 3306 es el estándar de MySQL)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/usersbd}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Tus credenciales
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:my-123456}

# El "mapa" para que Java sepa cómo hablar con MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración extra para que Spring Data JPA gestione las tablas
spring.jpa.show-sql=true

server.error.include-binding-errors=always
server.error.include-message=always